// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw2pf0iNy8tV-HkbxL8odT7Fy2qzxIDvM',
    appId: '1:586331341528:web:5d8f1a69382293a3cb4dad',
    messagingSenderId: '586331341528',
    projectId: 'componentes-c1e17',
    authDomain: 'componentes-c1e17.firebaseapp.com',
    storageBucket: 'componentes-c1e17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXscR-U8il_mGceCAhdEpZG7P_jfRw37I',
    appId: '1:586331341528:android:293e0cdf517e0672cb4dad',
    messagingSenderId: '586331341528',
    projectId: 'componentes-c1e17',
    storageBucket: 'componentes-c1e17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH_fxwuBL8IQopE_NBCfn5h8BYOFMhZJA',
    appId: '1:586331341528:ios:2618f453cadfcc5ccb4dad',
    messagingSenderId: '586331341528',
    projectId: 'componentes-c1e17',
    storageBucket: 'componentes-c1e17.appspot.com',
    iosBundleId: 'com.example.practica3',
  );
}
